---

- name: Install the apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: import redirection.io apt key
  apt_key:
    url: "{{ redirectionio_gpg_key_url }}"
    state: present

- name: Install redirection.io repository
  apt_repository:
    repo: "deb {{ redirectionio_packages_url }}deb {{ ansible_distribution_release }} main"
    state: present
  when: redirectionio_apache_module_main_version == 1

- name: Install redirection.io repository
  apt_repository:
    repo: "deb {{ redirectionio_packages_url }}deb/{{ redirectionio_apache_module_channel }}/{{ redirectionio_apache_module_main_version }} {{ ansible_distribution_release }} main"
    state: present
  when: redirectionio_apache_module_main_version > 1

- name: Update apt cache
  apt:
    update_cache: true

- name: Install libapache2-mod-redirectionio
  apt:
    name: "libapache2-mod-redirectionio={{ redirectionio_apache_module_version }}"
    state: present
