---

- name: Install the apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Import redirection.io apt key
  ansible.builtin.get_url:
    url: "https://packages.redirection.io/gpg.key"
    dest: /etc/apt/keyrings/redirectionio-archive-keyring.asc
    mode: '0644'

- name: Get dpkg architecture
  ansible.builtin.command: dpkg --print-architecture
  register: dpkg_architecture
  changed_when: false

- name: Install redirection.io repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ dpkg_architecture.stdout }} signed-by=/etc/apt/keyrings/redirectionio-archive-keyring.asc]
      {{ redirectionio_packages_url }}deb
      {{ ansible_distribution_release }}
      main
    state: present
  when: redirectionio_apache_module_main_version == 1

- name: Install redirection.io repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ dpkg_architecture.stdout }} signed-by=/etc/apt/keyrings/redirectionio-archive-keyring.asc]
      {{ redirectionio_packages_url }}deb/{{ redirectionio_apache_module_channel }}/{{ redirectionio_apache_module_main_version }}
      {{ ansible_distribution_release }}
      main
    state: present
  when: redirectionio_apache_module_main_version > 1

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install libapache2-mod-redirectionio
  ansible.builtin.apt:
    name: "libapache2-mod-redirectionio={{ redirectionio_apache_module_version }}"
    state: present
