---

- name: Add rpm repository key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ redirectionio_gpg_key_url }}"

- name: Install redirection.io repository
  ansible.builtin.yum_repository:
    name: redirectionio
    description: redirection.io
    baseurl: "{{ redirectionio_packages_url }}rpm/centos_{{ ansible_distribution_major_version }}"
    enabled: true
    gpgcheck: true
    state: present
  when: redirectionio_apache_module_main_version == 1

- name: Install redirection.io repository
  ansible.builtin.yum_repository:
    name: redirectionio
    description: redirection.io
    baseurl: >
      {{ redirectionio_packages_url }}rpm/{{ redirectionio_apache_module_channel }}/{{ redirectionio_apache_module_main_version }}/
      centos_{{ ansible_distribution_major_version }}
    enabled: true
    gpgcheck: true
    state: present
  when: redirectionio_apache_module_main_version > 1

- name: Update yum cache
  ansible.builtin.yum:
    update_cache: true

- name: Install libapache2-mod-redirectionio
  ansible.builtin.yum:
    name: "libapache2-mod-redirectionio-{{ redirectionio_apache_module_version }}"
    state: present
